spring:
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://49.234.32.190:3306/qr?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qr
    password: root
    initial-size: 5
    min-idle: 10
    max-active: 20
    max-wait: 60000
  devtools:
    restart:
      enabled: true
  resources:
    static-locations: classpath:static/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    cn.edu.zzuli.qridentify.dao: debug


qr:
  path:
    generate: http://192.168.1.19:8080/result?certificateCode=
    linux: /JavaDev/qrStatic
    windows: D:\WorkSpace\IdeaWorkSpace\qr\files


